# Generated by Django 4.2.27 on 2026-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://www.pomelvins.com/store/catering-1/", max_length=500
            ),
        ),
    ]
