# Generated by Django 4.2.27 on 2026-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://theme-assets.getbento.com/sensei/193414f.sensei/assets/images/catering-item-placeholder-704x520.png",
                max_length=500,
            ),
        ),
    ]
