# Generated by Django 4.2.27 on 2026-01-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_item_item_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="item_image",),
    ]
